version: '3'

services:
  app:
    platform: linux/x86_64
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s /home/node/app/.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    platform: linux/x86_64
    build: ./.docker/mysql
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root
